### ISSUE TITLE
Cannot apply "unflatten" to "h" (invalid type).

### ISSUE THREAD

**Issue by ghost** [nqpz/futcam#8]
```
# make
cd futcamlib && futhark pkg sync
futhark pyopencl --library futcamlib.fut
Error at futcamlib/misc.fut:36:26-27:
Cannot apply "unflatten" to "h" (invalid type).
Expected: [n₁₉ * m₂₀]t₁₈
Actual:   i64
If you find this error message confusing, uninformative, or wrong, please open an issue:
  https://github.com/diku-dk/futhark/issues
make: *** [Makefile:6: futcamlib.py] Error 2
```
https://github.com/nqpz/futcam/blob/0b784bfae17deba65ce9c199f21ec87048f1788d/futcamlib/misc.fut#L36

**Comment by nqpz** [comment]
Thanks, I had forgotten about this project!

I have fixed this issue and a few others like it and pushed my changes to the master branch. A few filters are broken, but mostly it works on my end. Please try to re-pull from master and see if this also fixes it for you. :slightly_smiling_face:

**Comment by ghost** [comment]
Yes, it builds for me with current Futhark in Nixpkgs. Thanks!
